// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZALEJLseSoYtqhPH4COchVYleMzazic',
    appId: '1:41267871760:web:fad206c77f9eb5ea9d0a95',
    messagingSenderId: '41267871760',
    projectId: 'bookswap-app-89255',
    authDomain: 'bookswap-app-89255.firebaseapp.com',
    storageBucket: 'bookswap-app-89255.firebasestorage.app',
    measurementId: 'G-GW7F0JN8Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiVbYY3VZOZWBpMSK9DwwRx8RZXwAkVa8',
    appId: '1:41267871760:android:b1e41c74418ae84b9d0a95',
    messagingSenderId: '41267871760',
    projectId: 'bookswap-app-89255',
    storageBucket: 'bookswap-app-89255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzhGxtB8TT76Hlex2lm_K5gvgHJtIJFc',
    appId: '1:41267871760:ios:f325efda33a57de29d0a95',
    messagingSenderId: '41267871760',
    projectId: 'bookswap-app-89255',
    storageBucket: 'bookswap-app-89255.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzhGxtB8TT76Hlex2lm_K5gvgHJtIJFc',
    appId: '1:41267871760:ios:f325efda33a57de29d0a95',
    messagingSenderId: '41267871760',
    projectId: 'bookswap-app-89255',
    storageBucket: 'bookswap-app-89255.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMZALEJLseSoYtqhPH4COchVYleMzazic',
    appId: '1:41267871760:web:8117eafb95daaf1f9d0a95',
    messagingSenderId: '41267871760',
    projectId: 'bookswap-app-89255',
    authDomain: 'bookswap-app-89255.firebaseapp.com',
    storageBucket: 'bookswap-app-89255.firebasestorage.app',
    measurementId: 'G-S4QWM0VJMK',
  );
}
